title: "club418"
description: "Association pour la promotion du numérique citoyen"
url: "https://club418.github.io"
baseurl: "" # vide si le dépôt s'appelle club418.github.io
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
permalink: pretty

minima:
  skin: classic # options : classic, dark, solarized
  social_links:
    github: club418
    twitter: club_418
