services:
  jekyll:
    image: jekyll/jekyll:latest
    container_name: club418-jekyll
    command: jekyll serve --livereload --force_polling --config _config.yml,_config_dev.yml
    ports:
      - "4000:4000"      # Site web
      - "35729:35729"    # LiveReload
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development
      - TZ=Europe/Paris
    restart: unless-stopped
